#Custom distro for raspberrypi 02w, 3, 4

DISTRO = "rpi-distro"
DISTRO_NAME = "Vlab reference distribution"
DISTRO_VERSION = "2026.06"

#init manager
INIT_MANAGER = "systemd"

#PACKAGE MANAGER TYPE
PACKAGE_CLASSES ?= "package_ipk"

#Distro features
DISTRO_FEATURES = "\
                   bluetooth \
                   ipv4 \
                   ipv6 \
                   ldconfig \
                   usbgadget \
                   usbhost \
                   wifi \
                   xattr \
                   zeroconf \
                   x11 \
                   vfat \
                   wayland \
                   usrmerge \
                   "

#prevent the installation of all recommended packages
NO_RECOMMENDATIONS ="1"

#Use one tmp directory (this to avoid the creation of the directory (tmp-glic) 
TCLIBCAPPEND = ""


